### ISSUE TITLE
Laravel 5.4 compatibility 

### ISSUE THREAD

**Issue by jgerbes** [cviebrock/eloquent-taggable#43]
Has this package been updated for Laravel 5.4?

I get this error when attempting to tag a model:

```
[2017-02-01 10:47:30] local.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'taggable_taggables.tag_tag_id' in 'field list'' in /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Connection.php:319
Stack trace:
#0 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Connection.php(319): PDO->prepare('select `taggabl...')
#1 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select `taggabl...', Array)
#2 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select `taggabl...', Array, Object(Closure))
#3 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select `taggabl...', Array, Object(Closure))
#4 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1719): Illuminate\Database\Connection->select('select `taggabl...', Array, true)
#5 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1703): Illuminate\Database\Query\Builder->runSelect()
#6 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(485): Illuminate\Database\Query\Builder->get(Array)
#7 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php(486): Illuminate\Database\Eloquent\Builder->getModels()
#8 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsToMany.php(466): Illuminate\Database\Eloquent\Relations\BelongsToMany->get()
#9 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(406): Illuminate\Database\Eloquent\Relations\BelongsToMany->getResults()
#10 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(385): Illuminate\Database\Eloquent\Model->getRelationshipFromMethod('tags')
#11 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(315): Illuminate\Database\Eloquent\Model->getRelationValue('tags')
#12 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1221): Illuminate\Database\Eloquent\Model->getAttribute('tags')
#13 /Users/jasongerbes/Sites/blog/vendor/cviebrock/eloquent-taggable/src/Taggable.php(96): Illuminate\Database\Eloquent\Model->__get('tags')
#14 /Users/jasongerbes/Sites/blog/vendor/cviebrock/eloquent-taggable/src/Taggable.php(39): App\Item->addOneTag('12 month warran...')
#15 /Users/jasongerbes/Sites/blog/app/Http/Controllers/ArticleController.php(52): App\Item->tag(Array)
#16 [internal function]: App\Http\Controllers\ArticleController->show(Object(App\Item))
#17 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#18 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('show', Array)
#19 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\ArticleController), 'show')
#20 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#21 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(559): Illuminate\Routing\Route->run()
#22 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /Users/jasongerbes/Sites/blog/vendor/barryvdh/laravel-cors/src/HandleCors.php(34): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#31 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#36 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#37 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#38 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /Users/jasongerbes/Sites/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 /Users/jasongerbes/Sites/blog/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 /Users/jasongerbes/.composer/vendor/laravel/valet/server.php(106): require('/Users/jasonger...')
#55 {main}
```

**Comment by cviebrock** [comment]
Looks like maybe you didn't run the migrations to generate the taggable table?

**Comment by jgerbes** [comment]
Here's the migration I ran:

`public function up()
    {
        Schema::create('taggable_tags', function (Blueprint $table) {
            $table->increments('tag_id');
            $table->string('name');
            $table->string('normalized');
            $table->timestamps();
        });

        Schema::create('taggable_taggables', function (Blueprint $table) {
            $table->unsignedInteger('tag_id');
            $table->unsignedInteger('taggable_id');
            $table->string('taggable_type');
            $table->timestamps();
        });
    }`

Attempting to tag a model adds the tag to the "taggable_tags" table, but it fails to associate it with the model in the "taggable_taggables" table.

I didn't encounter this problem with Laravel 5.3, but am with my new 5.4 project.

**Comment by cviebrock** [comment]
Weird.  I haven't explicitly tested the package with L5.4, but having it change `tag_id` to `tag_tag_id` seems like an odd thing to happen.  I'll investigate.

**Comment by jgerbes** [comment]
Thanks :) I appreciate your help

**Comment by cviebrock** [comment]
Want to try the `2.1.0-beta` version of the package and see if that works for you with L5.4?

**Comment by jgerbes** [comment]
It works perfectly! Thanks for getting this sorted so quickly.

I see that you had to explicitly state the foreign key for the morph many relationship. Perhaps it has something to do with the way that Laravel 5.4 now handles foreign key constraints:

https://laravel.com/docs/5.4/upgrade
> If the foreign key is not explicitly specified when defining a relationship, Eloquent will now use the table name and primary key name for the related model to build the foreign key.

**Comment by cviebrock** [comment]
Ah cool.  I haven't had the time/direction to port any of my projects to L5.4, so I wasn't aware of all the changes.  Good to know this one, since I rarely use `id` as the primary key field name in my tables.  Thanks!

I'll fix up some minor issues and push a stable release shortly.

**Comment by jgerbes** [comment]
Hey, any updates on the stable 2.1.0 release?

**Comment by cviebrock** [comment]
Tagging it now.

**Comment by Corys8646** [comment]
I upgraded my laravel app this evening to 5.4 and also upgraded to 2.1 version of this. However, whenever I try to run php artisan migrate, I receive an error that the tables already exist. The migrations were ran when I initially did the install and have models already tagged.

```[Illuminate\Database\QueryException]                                                                                                                                                                                                           
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'taggable_tags' already exists (SQL: create table `taggable_tags` (`tag_id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `normalized` varch  
  ar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci)                                                                                                                
                                                                                                                                                                                                                                                 
                                                                                                 
  [Doctrine\DBAL\Driver\PDOException]                                                            
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'taggable_tags' already exists  
```

If I revert this change that was made in the service provider class, the problem goes away.

```
-        if (!class_exists('CreateTaggableTable')) {
 -            // Publish the migration
 -            $timestamp = date('Y_m_d_His', time());
 -            $src = __DIR__ . '/../resources/database/migrations/0000_00_00_000000_create_taggable_table.php';
 -            $dst = database_path('migrations/' . $timestamp . '_create_taggable_table.php');
 -
 -            $this->publishes([
 -                $src => $dst,
 -            ], 'migrations');
 -        }
 +        $this->loadMigrationsFrom(
 +            __DIR__.'/../resources/database/migrations'
 +        );
```

**Comment by cviebrock** [comment]
Sounds like it's trying to run the migrations twice.  I think I just need to add some extra logic to the migration, using `Schema::hasTable('taggable_tags')`.

I'm not at my laptop right now, but will fix this shortly.  Thanks!

**Comment by cviebrock** [comment]
The 2.1.1 release should fix this for you!  LMK that it works?

**Comment by Corys8646** [comment]
awesome...that works..it still showed that it ran the migration and put another entry into my migrations table, but didn't appear to touch anything on the tables themselves. Thanks!
